### ISSUE TITLE
ec2-credential service needs more work

### ISSUE THREAD

**Issue by ptribble** [omniosorg/omnios-build#1247]
Running on AWS, we often fail to pick up the root ssh key pair.

This is especially common at first boot.

The problem is twofold: first, the ec2-credential service doesn't actually wait for the network to be up, and second, the script tries once only. (I suspect first boot is slower, delaying network bringup slightly, which pretty much guarantees failure.)

I suggest using the Tribblix versions, which have been hardened:

https://github.com/tribblix/build/blob/fff047cc063897064d45c3891d7b1ec267545c3b/patches/ec2-credential.xml

https://github.com/tribblix/build/blob/fff047cc063897064d45c3891d7b1ec267545c3b/patches/install-ec2-credential

**Comment by hadfl** [comment]
thanks @ptribble,

integrated: https://github.com/omniosorg/omnios-build/pull/1248
