### ISSUE TITLE
Problem with wrap_socket()'d sockets and settimeout() in python2 and 3 in r151030

### ISSUE THREAD

**Issue by whorfin** [omniosorg/omnios-build#1424]
I have a python program which maintains a TLS socket connection to another server at an IPv4 address on the LAN.  The server has a 30 sec heartbeat, so I ultimately do something like this:
`self.socket.settimeout(45.0)`
The socket is `wrap_socket()`'d for `ssl.PROTOCOL_TSLv1`

Everything was fine on `r151022`, with the code running against the OS's `python2.7`
I updated to `r151030`, and the program immediately broke.  `Errno 11` [Resource temporarily unavailable] on `do_handshake()` call.

Without the `settimeout()`, it worked.
Dropping the `do_handshake_on_connect=False`/`do_handshake()` caused a different error in the `wrap_socket()` call if the `settimeout()` were still present.

Ported the program to `python3` as that seems to be the thing to do, still the same failure.
(in this case, the `python3.5` which again is part of `r151030` repo)
Adapted to use `ssl.SSLContext()` for `wrap_socket()` and still fail town.

In desperation, tried `python3.7` from `SmartOS 2018Q4` `pkgin`, and that worked exactly as expected.  Previous [working under `python2.7` in `r151022`] version worked as expected with `SmartOS` version of `python2.7` as well.

...which leads me to the inevitable conclusion that something is wrong with `r151030` python interaction[s] with SSL/OpenSSL/etc, `settimeout()` in particular.  I'm very surprised by this, which is why I spent so long banging my head against permutations in my code, and forward-porting to current best practices.  I could not find any references to this, but those search terms aren't so easy

For reference, here's the relevant bit of code in the original version:
```
raw_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
self.socket = ssl.wrap_socket(raw_socket, do_handshake_on_connect=False, ssl_version=ssl.PROTOCOL_TLSv1)
self.socket.settimeout(45.0)
self.socket.connect((self.address, self.port))
self.socket.do_handshake()
```
and here is the more modern version:
```
raw_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
context.verify_mode = ssl.CERT_NONE
context.check_hostname = False
self.socket = context.wrap_socket(raw_socket, do_handshake_on_connect=False)
self.socket.settimeout(45.0)
self.socket.connect((self.address, self.port))
self.socket.do_handshake()

```

both fail on `r151030`, the first is known to work on `r151022` and both work on `SmartOS 2018Q4` versions of python

Cheers

**Comment by citrus-it** [comment]
Thanks for the detailed bug report. I will look into this.
I wonder if this is because of the change from OpenSSL 1.0 to 1.1 in r151030. The pkgsrc version may still be using 1.0

I made a quick stand-alone test program which works. Is it possible that your TLS/SSL server is using something that has been removed in OpenSSL 1.1?

```python
#!/usr/bin/python

import socket, ssl
from pprint import pprint

raw_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
socket = ssl.wrap_socket(raw_socket,
    do_handshake_on_connect=False, ssl_version=ssl.PROTOCOL_TLSv1)
socket.settimeout(45.0)
socket.connect(('129.132.2.8', 443))
socket.do_handshake()
pprint(socket.cipher())
```
```
build% uname -a
SunOS build 5.11 omnios-r151030-632fca26eb i86pc i386 i86pc
build% python3 wrap.py
('ECDHE-RSA-AES128-SHA', 'TLSv1.0', 128)
build% python2 wrap.py
('ECDHE-RSA-AES128-SHA', 'TLSv1.0', 128)
```

**Comment by whorfin** [comment]
More hair pulling, as your example immediately worked for me.
BTW, I don't think it is an issue with server support, as it works without the timeout.

I have a minimal repro case now, and the second confounding factor appears to be threading.
```
#!/usr/bin/python

import socket, ssl
from pprint import pprint
from threading import Thread


class ListenerThread(Thread):
    def __init__(self, address, port):
        Thread.__init__(self)
        self.address = address
        self.port = port
        self.socket = None
    def run(self):
        print("Starting connection")
        try:
            raw_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self.socket = ssl.wrap_socket(raw_socket,
                do_handshake_on_connect=False, ssl_version=ssl.PROTOCOL_TLSv1)
            self.socket.settimeout(45.0)
            self.socket.connect((self.address, self.port))
            self.socket.do_handshake()
            pprint(self.socket.cipher())
        except Exception as e:
            print("connection failed: " + str(e))
        print("Connected succeeded")

listen = ListenerThread('myserver', <myport>)
listen.start()
```
Running this, I see:
```
$ python3 python-ssl-debug.py
Starting connection
connection failed: [Errno 11] Resource temporarily unavailable
$ python3.7 python-ssl-debug.py
Starting connection
('AES256-SHA', 'TLSv1/SSLv3', 256)
$ which python3
/usr/bin/python3
$ which python3.7
/opt/local/bin/python3.7
```
and for good measure:
```
$ python2 python-ssl-debug.py
Starting connection
connection failed: [Errno 11] Resource temporarily unavailable
Connected succeeded
$ /opt/local/bin/python2 python-ssl-debug.py
Starting connection
('AES256-SHA', 'TLSv1/SSLv3', 256)
Connected succeeded
```
As you speculated, the pkgin/SmartOS version has openssl-1.0.2
And, again, if the settimeout() is removed, it works with the system Python install
Finally, 
```
$ uname -a
SunOS pergamum 5.11 omnios-r151030-632fca26eb i86pc i386 i86pc illumos
```

**Comment by whorfin** [comment]
...still busted after the Python updates of r151030z , for both python2 and python3

**Comment by citrus-it** [comment]
If this is still broken in r151034, then we need to do more investigation.

**Comment by whorfin** [comment]
Can confirm it is still broken in latest r151030
There should be enough info in the examples to confirm/deny in -034

**Comment by citrus-it** [comment]
I've been doing some more digging into this, and it appears to be a problem with the OpenSSL library that OmniOS ships, rather than python itself. In a `pkgsrc`-branded zone:

```
root@pkgsrc:~# python3 ./test
Starting connection thread
connection failed: [Errno 11] Resource temporarily unavailable
Finished connection thread
```
versus, with pkgsrc's openssl library:
```
root@pkgsrc:~# LD_PRELOAD=/opt/local/lib/libssl.so python3 ./test
Starting connection thread
('ECDHE-ECDSA-CHACHA20-POLY1305', 'TLSv1.2', 256)
Finished connection thread
```

**Comment by citrus-it** [comment]
I have a fix for this which will be included in the next weekly releases for all supported versions. Thanks!

**Comment by whorfin** [comment]
Thank you!
The LD_PRELOAD trick is very clever and I wish I'd thought to try that to help find the culprit.
Can confirm same results on '030:
```
$ which python3
/usr/bin/python3
$ python3 python-ssl-debug.py
Starting connection thread
connection failed: [Errno 11] Resource temporarily unavailable
Finished connection thread
$ env LD_PRELOAD=/opt/local/lib/libssl.so python3 python-ssl-debug.py
Starting connection thread
('AES256-SHA', 'SSLv3', 256)
Finished connection thread
$ uname -a
SunOS solaroid 5.11 omnios-r151030-913ede3ff3 i86pc i386 i86pc illumos
```

**Comment by citrus-it** [comment]
Today's releases of r151030bm, r151032am and r151034m include a fix for this issue.
Please can you update and confirm that it's resolved for you?

Thanks!

**Comment by whorfin** [comment]
Confirmed!

Resolved; thanks so much for fixing and pushing this out

**Comment by citrus-it** [comment]
No problem, sorry it took so long to track down!
