### ISSUE TITLE
"gcc-ar" script doesn't and work and breaks Meson Build

### ISSUE THREAD

**Issue by matthias-scheler** [omniosorg/omnios-build#1487]
GCC 7 (and GCC 5 on older versions of OmniOS) comes with a script called _gcc-ar_ which doesn't work:

```
> which gcc-ar
/opt/gcc-7/bin/gcc-ar
> gcc-ar
ar: bad option: --
usage: ar -d[-SvV] archive file ...
       ar -m[-abiSvV] [posname] archive file ...
       ar -p[-vV][-sS] archive [file ...]
       ar -q[-cuvSV] [-abi] [posname] [file ...]
       ar -r[-cuvSV] [-abi] [posname] [file ...]
       ar -t[-vV][-sS] archive [file ...]
       ar -x[-vV][-sSCT] archive [file ...]
```

This is becoming a major problem because Meson Build (see http://mesonbuild.com/ ) uses _gcc-ar_ when available. This causes e.g. failures when trying to build glib2 under OmniOS.

The problem is as far as I can tell that _gcc-ar_ expect _ar_ to be the GNU version which is called _gar_ under OmniOS. However even using _gar_ under OmniOS is problematic because it is a 32bit binary that uses C standard I/O and is therefore limited to 256 open files which breaks the build of _MesaLib_. The best solution I've found so far is to install a 64bit _binutils_ and make sure that the directory with its _ar_ binary is early enough in the command line path.

**Comment by citrus-it** [comment]
Thanks for the report, we'll have a look.

The `library/python-3/meson-35` package that we provide is patched to work around this (and other things) - see https://github.com/omniosorg/omnios-build/blob/master/build/python35/meson/patches/illumos_gcc.patch

We do now build `glib2` with meson too - see https://github.com/omniosorg/omnios-build/blob/master/build/glib/build.sh#L85
