### ISSUE TITLE
IO read\write problems

### ISSUE THREAD

**Issue by acidorius** [omniosorg/omnios-build#1495]
Hello, community!

We use OmniOS v11 r151014 as our production storage. It consists of three pools on three different disk types (SATA, SAS and SSD). And this setup started to working quite bad. Deeper investigation leaded us to issue, that lies in OS layer. The problem is next - when we initiate hard write on one zpool, the other zpool undergoing in high read lack.

All detailed tests was done on newer OmniOS r151030 with all updates and issue still encounters.

Some info:

- zpools are located on different devices, so it is not the device issue;
- reproducing the tests on one zpool cause global IO drop, but it is exprected. Also, during write operations on zpool, read\write IO on same zpool higher, then read\write IO on separate;
- the problem not on higher layer, because tests was done in up to down order - from the VM layer and to the OS;
- this problem was not found on same setup with ZFS on FreeBSD and zfsonlinux.

Some numbers acquired using fio and two VMs and dd directly in system:

Tests on the Solaris host:

| Test parameters | Read only | Write only |
| -------------------- | ------------- | ------------- |
| 2 sync write | 209715200 bytes transferred in 0,409412 secs (489MB/sec)209715200 bytes transferred in 0,344487 secs (581MB/sec)209715200 bytes transferred in 0,353940 secs (565MB/sec) | 209715200 bytes transferred in 7,553999 secs (26,5MB/sec)209715200 bytes transferred in 6,632902 secs (30,2MB/sec)209715200 bytes transferred in 8,325661 secs (24,0MB/sec)|
| no write | 209715200 bytes transferred in 0,199469 secs (1003MB/sec)209715200 bytes transferred in 0,202878 secs (986MB/sec)209715200 bytes transferred in 0,202665 secs (987MB/sec) | 209715200 bytes transferred in 6,172171 secs (32,4MB/sec)209715200 bytes transferred in 5,811409 secs (34,4MB/sec)209715200 bytes transferred in 6,073459 secs (32,9MB/sec) |

Tests on FreeBSD host:

| Test parameters | Read only | Write only |
| -------------------- | ------------- | ------------- |
| 2 sync write | 209715200 bytes transferred in 0,204883 secs (976MB/sec)209715200 bytes transferred in 0,203778 secs (981MB/sec)209715200 bytes transferred in 0,202213 secs (989MB/sec) | 209715200 bytes transferred in 6,292447 secs (31,8MB/sec)209715200 bytes transferred in 5,667027 secs (35,3MB/sec)209715200 bytes transferred in 5,957812 secs (33,6MB/sec) |
| no write | 209715200 bytes transferred in 0,200827 secs (996MB/sec)209715200 bytes transferred in 0,202766 secs (986MB/sec)209715200 bytes transferred in 0,201810 secs (991MB/sec) | 209715200 bytes transferred in 6,023156 secs (33,2MB/sec)209715200 bytes transferred in 6,086489 secs (32,9MB/sec)209715200 bytes transferred in 6,172171 secs (32,4MB/sec) |

Tests were done using 2 zpools mounted localy via iscsi. All system parameters are in default state. Using the parameters from FreeBSD on OmniOS gave no improvement.

**Comment by oetiker** [comment]
Questions:

* do the machines have the same amount of RAM ?
* zpools equally fragmented on both systems
* do the zpools contain the same amount of free space ?

**Comment by acidorius** [comment]
All tests were made on one server in dev environment, so RAM and free space are not the reasons. 

Both, FreeBSD and OmniOS, are using 4k block size for zpools, if question about fragmentation was correctly understood.

**Comment by oetiker** [comment]
have you performed the tests on a drive with exactly the same content? high fragmentation on a zfs pool can cause dramatic performance degradation depending on the workload ...

**Comment by acidorius** [comment]
The tests done with random 4gb sized data with same blocked file via _dd if=/dev/urandom of=/path/to/test.file bs=4k count=512000; done_

Also, the problem is possibly in workload, but not in zfs, because both OS uses same zfs with same fragmentation, but the problem happened only in one system. 

The question is why separate zpools located on separated disks affect each other inside one system, when it is expected than each zpool have its own IO stats?
