### ISSUE TITLE
gcc8: wrong path for build-time-tools 

### ISSUE THREAD

**Issue by alhazred** [omniosorg/omnios-build#1741]
https://github.com/omniosorg/omnios-build/blob/4451d9eb7b3924d89a6105471f1341947503cf1c/build/gcc8/build.sh#L90

Must be TRIPLET32

**Comment by citrus-it** [comment]
As far as I can see, `$TRIPLET64` is correct for the current bloody.

```
% pkg contents gnu-binutils
PATH
...
usr/gnu/x86_64-pc-solaris2.11/bin
usr/gnu/x86_64-pc-solaris2.11/bin/ar
usr/gnu/x86_64-pc-solaris2.11/bin/as
usr/gnu/x86_64-pc-solaris2.11/bin/ld
```

If you're building anything on a previous release, make sure you have switched to the correct branch.

**Comment by alhazred** [comment]
Ah, yes. Sorry for noise.
