### ISSUE TITLE
Support for BCM57416 network Supermicro 1113S-WN10RT

### ISSUE THREAD

**Issue by prcnjg** [omniosorg/omnios-build#1855]
We got a new server (Supermicro 1113S-WN10RT) with BCM57416 10GB network but omnios (r151034) is not showing it in dladm.
When running prtconf -d | grep Broadcom it's showing pci15d9,16d8 (pciex14e4,16d8) [Broadcom Inc. and subsidiaries BCM57416 NetXtreme-E Dual-Media 10G RDMA Ethernet Controller] (driver not attached)

**Comment by citrus-it** [comment]
Unfortunately that's not a supported part in OmniOS. I'll investigate how hard it would be to add.

**Comment by citrus-it** [comment]
Apparently this interface family (Broadcom -C and -E series) needs a completely new driver. 
There is a half written one for illumos but the person doing the work no longer has access to a card to continue development. Sorry I don't have better news.

**Comment by prcnjg** [comment]
I can give access to the machine if this helps. We are testing the new server the next couple of days (out of production).
