### ISSUE TITLE
Default zsh PS1 string is borken

### ISSUE THREAD

**Issue by sjorge** [omniosorg/omnios-build#1862]
After installing zsh on OmniOS bloody using:
```
pkg install zsh
```

Then running `zsh`
```
root@omniosce:~# zsh
\u@\h:\w\$
```

This might be the same cause as to why the PS1 is broken in `omni env` too. But andyf mentioned it was fine for him and he was using zsh... so I thought I'd try that and hit this.

**Comment by moetiker** [comment]
thanks I have added a pull request to set a working pompt
PROMPT='%n@%m:%~ $ '

**Comment by citrus-it** [comment]
This only ever affected the root user, and was fixed in #1863
