### ISSUE TITLE
open-vm-tools unsupported in LTS 151030 on latest ESXi 6.0

### ISSUE THREAD

**Issue by lchegde** [omniosorg/omnios-build#1901]
With the latest update for ESXi 6.0 the open-vm-tools package for LTS 151030 guests shows up as 'Running - Unsupported' in the VM console. It is unclear whether it is the wrong version or just something with version tagging as the ESXi patch info linked below lists VM-Tools 10.3.10 as the latest/correct version for Solaris 10 and up.

ESXi 6.0 version info:
VMware ESXi 6.0, Patch Release ESXi600-202002001 Build 15517548
https://docs.vmware.com/en/VMware-vSphere/6.0/rn/esxi600-202002001.html#esxi600-202002402-bg-resolved

Omni version info:
```
xxx@zfs:~$ uname -a
SunOS zfs 5.11 omnios-r151030-644d21f0e7 i86pc i386 i86pc illumos
xxx@zfs:~$ pkg info system/virtualization/open-vm-tools
          Name: system/virtualization/open-vm-tools
       Summary: Open Virtual Machine Tools
   Description: The Open Virtual Machine Tools project aims to provide a suite
                of open source virtualization utilities and drivers to improve
                the functionality and user experience of virtualization. The
                project currently runs in guest operating systems under the
                VMware hypervisor.
      Category: System/Virtualization
         State: Installed
     Publisher: omnios
       Version: 10.3.10
        Branch: 151030.0
Packaging Date: 26. april 2019 kl. 23:22:22
          Size: 1.40 MB
          FMRI: pkg://omnios/system/virtualization/open-vm-tools@10.3.10-151030.0:20190426T232222Z
    Source URL: https://mirrors.omniosce.org/open-vm-tools/open-vm-tools-10.3.10-12406962.tar.gz
```

**Comment by hadfl** [comment]
I opened a PR, updating `open-vm-tools` to `11.1.0` for r151030: https://github.com/omniosorg/omnios-build/pull/1902

I also pushed a hot-fix, in case you have time to test:
`pkg apply-hot-fix https://hf.omniosce.org/r151030/open-vm-tools-11.1.0.p5m`

**Comment by lchegde** [comment]
Wow, that was quick! I tested the hotfix, its all good now:  `Running (Current)`

**Comment by hadfl** [comment]
The updated `open-vm-tools` will be part of  `r151030bf` to be released tomorrow.
