### ISSUE TITLE
illumos-omnios already built (no nightly.lock present...)

### ISSUE THREAD

**Issue by yuleihua** [omniosorg/omnios-build#1956]
Hi 
   I  want to build omnios-build, but has this error:

[2] /devos/illumos-omnios already built (no nightly.lock present...)
[2] Prebuilt illumos not present, aborting.

   Could you help me?!

**Comment by hadfl** [comment]
to build a **full** `omnios-build` you need to build `illumos-omnios` first, as `omnios-build` takes in packages built in `illumos-omnios`.

the error message you hit states that it can't find a built `illumos-omnios`.

have a look at the documentation about building omnios:
https://omniosce.org/dev/build_instructions.html

if you still face issues, let us know.

**Comment by yuleihua** [comment]
thanks，I solved the problem as you suggested. I like solaris,  now i like omnios too.  There's a lot of innovation in omnios！
