### ISSUE TITLE
Remove C-states workaround lifted from SmartOS

### ISSUE THREAD

**Issue by jclulow** [omniosorg/omnios-build#1984]
Hi folks,

As I was investigating a somewhat related issue, I found that OmniOS ships by default an `/etc/system` tunable value that totally disables deep C-states:

```
*
* Disable c-states.
*
set idle_cpu_no_deep_c=1
```

Seen here: https://github.com/omniosorg/omnios-build/blob/f045abc11b019d6582b020ce9d539260a2a85fb7/build/system/files/system#L38-L41

This workaround is unlikely to be necessary, especially in the face of subsequent bug fixes to pcplusmp/apix, etc.  Leaving this enabled likely increases the power consumption of idle or partially idle CPUs.  Indeed, it was suggested to me that it also prevents things like Turbo Boost from working correctly.

It'd be good to get this done ASAP in bloody so that it has some soak time.

**Comment by citrus-it** [comment]
I've published an updated `system/defaults` package for bloody, and changed the setting on my production (r34) servers with:

```
# echo set idle_cpu_no_deep_c=0 > /etc/system.d/cstates
```

**Comment by jclulow** [comment]
Thanks on both counts!  Please let me know if you see any new weird issues.
