### ISSUE TITLE
SMB is unusable with macOS 11 Big Sur

### ISSUE THREAD

**Issue by gnattu** [omniosorg/omnios-build#2112]
Big Sur Mac (Intel) can connect the OmniOS smb share, can login, can list files, but cannot perform any further operation beyond that. The attempt to open/delete a file will result in a non-responding finder.

**Comment by mvwieringen** [comment]
@gnattu guess this one can be closed after todays release as that has a fix for the above issue. Please check and close this
when its fixed.

**Comment by gnattu** [comment]
I can confirm the issue is fixed in today's update. Thank you.
