### ISSUE TITLE
p7zip truncates password to 8 chars when entered from terminal vs command-line arg

### ISSUE THREAD

**Issue by whorfin** [omniosorg/omnios-build#2457]
Observed with `7z` and `7za` from
```
 pkg:/compress/p7zip@16.2-151038.0
```

Basically, because Solaris nerfed `getpass()`, `getpassphrase()` should be called instead on Illumos.

Reported upstream:
https://sourceforge.net/p/p7zip/bugs/230/

This is rather insidious as it "self-consistent" - one thinks one is making encrypted archives with long passwords which can't be opened on eg Linux, or vice-versa, but which can be expanded only the system on which they were made.   ..until one realizes one can open them on Linux by typing only 8 characters, but on Illumos, one must currently use the command-line-passed password form.

**Comment by hadfl** [comment]
thank you for the report.
