### ISSUE TITLE
OmniOS installer - bug in password entry

### ISSUE THREAD

**Issue by sgsthor** [omniosorg/omnios-build#2507]
The password entry in the OnmiOS installer has a max-length of 20 characters for a password. This is incorrect handling as Illumos and Solaris allow for MUCH longer passwords.

I have a 24 char password and I could not log into a fresh installation of OmniOS until I started dropping (one by one) characters off of the end of my password until I was at 20 left.

This should be extended to at least 64 characters.

**Comment by sgsthor** [comment]
This is still a bug and should still be addressed.

**Comment by jakubtalich** [comment]
I second this. It should be fixed.
