### ISSUE TITLE
libltdl from libtool has the wrong 64-bit search path

### ISSUE THREAD

**Issue by jclulow** [omniosorg/omnios-build#2799]
As an OS that supports both 32- and 64-bit binaries, we provide dynamic libraries in 32- and 64-bit versions.  Generally 32-bit libraries are found in the base library directory (e.g., `/usr/lib`) and 64-bit libraries are found in the 64-bit library directory (e.g., `/usr/lib/64` also known as `/usr/lib/amd64`).

Libtool provides a support library, `libltdl`, which seeks to make uniform the process of loading additional shared libraries; e.g., as loadable plugins.  Unfortunately it hard-codes the search path `/lib:/usr/lib`, which is correct for 32-bit processes but not for 64-bit processes.

It would seem to be sufficient to set `LT_SYS_LIBRARY_PATH='/lib/64:/usr/lib/64'` during `configure` for the 64-bit build:

```diff
diff --git a/build/libtool/build.sh b/build/libtool/build.sh
index 55899b5c..52956cc1 100755
--- a/build/libtool/build.sh
+++ b/build/libtool/build.sh
@@ -28,6 +28,7 @@

 PROG=libtool
 VER=2.4.6
+DASHREV=1
 PKG=developer/build/libtool  ##IGNORE##
 SUMMARY="unused; replaced below"
 DESC="$SUMMARY"
@@ -42,6 +43,15 @@ CONFIGURE_OPTS="
     --disable-static
 "

+#
+# The libltdl library encodes a search path for library files that is correct
+# for 32-bit processes, but needs to be amended for 64-bit processes so that it
+# matches the system default:
+#
+CONFIGURE_OPTS_WS_64="
+    LT_SYS_LIBRARY_PATH=/lib/64:/usr/lib/64
+"
+
 init
 download_source $PROG $PROG $VER
 patch_source
```

**Comment by citrus-it** [comment]
Thanks, I've opened a PR to fix this, can you let me know whether you'd like to be listed as the author and/or have a copyright line etc.?
I haven't updated `DASHREV` for bloody since we don't maintain that there (but we'll bump DASHREV if we backport this to a stable release), and I used the defined `$ISAPART64` variable

**Comment by jclulow** [comment]
I don't need to be author!  Thanks for getting it!
