### ISSUE TITLE
/usr/lib/cpp should define __illumos__

### ISSUE THREAD

**Issue by jclulow** [omniosorg/omnios-build#2879]
I think `/usr/lib/cpp` should probably define the new `__illumos__` macro we've specified in [illumos bug 13726](https://www.illumos.org/issues/13726).  I'm not really sure where [the source for `cpp` comes from?](https://github.com/omniosorg/omnios-build/blob/master/build/cpp/build.sh#L38)  At some point in the last couple of years, I split out the source that I think we were using in SmartOS into [illumos/cpp](https://github.com/illumos/cpp) on GitHub; I'm not sure how similar that source is, or if we should fix this there first, or what.

cc @richlowe

**Comment by richlowe** [comment]
It's possible they take the old closed binary?  Last I knew only smartos was using the one from the distant past and someone improved.   I don't think we even finished actually fixing the one in smartos ever

**Comment by hadfl** [comment]
IIRC we use `cpp` from schily tools:
http://schilytools.sourceforge.net/

**Comment by jclulow** [comment]
How does that source get to be "cpp" that the download function can access?

**Comment by hadfl** [comment]
The download function pulls from our omnios mirror by default. Given the git history, it looks like the (schily) `cpp` source was initially added to the `omnios-build` repository, then been tar.gz'ed later and put on our mirror.

**Comment by citrus-it** [comment]
It looks like we need a fairly simple patch, as per the linked PR, since our compiler has been defining this for a while.
I'll compare the source you've put at illumos/cpp

**Comment by citrus-it** [comment]
Github illumos/cpp looks to be a year newer..
```diff
-/* Copyright (c) 2011 Joyent, Inc. All rights reserved. */
+/* Copyright (c) 2012 Joyent, Inc. All rights reserved. */
```

Not a great many changes, but some cleanups.
The repository should probably gain the licence files
* caldera.license
* schilix.license
