### ISSUE TITLE
update: security/sudo

### ISSUE THREAD

**Issue by citrus-it** [omniosorg/omnios-build#30]
1.8.7 -> 1.8.20p2

**Comment by danmcd** [comment]
BE CAREFUL!

I never upgraded this because it took in a bunch of stuff from Oracle which broke things.  If you have proper patches that make it work properly, go ahead, but this is not just a version-bump-upgrade.

**Comment by citrus-it** [comment]
Thanks, that's good to know.
I'm raising these for everything that's out of date so we can assess or do it.
The new audit stuff in the newer sudo version is supported by a recent commit in illumos-gate at least.

**Comment by hadfl** [comment]
and, it depends on this commit https://github.com/illumos/illumos-gate/commit/73177167911de9eef96901d8f6d3cb6be7c67574
