### ISSUE TITLE
pcre2demo(3) is very incorrectly formatted

### ISSUE THREAD

**Issue by richlowe** [omniosorg/omnios-build#3338]
pcre2demo(3) from pkg:/library/pcre2@10.42-151047.0 contains an entire demo program in the 'NAME' of the manual page and has other problems that make the formatting, or it even being a manual page, seem questionable.

Most annoyingly this makes `man -k <anything in that file>` display the whole demo code.

**Comment by hadfl** [comment]
Thanks for the bug report. I'll have a look.
