### ISSUE TITLE
update: python extensions

### ISSUE THREAD

**Issue by citrus-it** [omniosorg/omnios-build#40]
Consider upgrading the python extensions below. This is used predominantly by pkg(5).

* library/python-2/cherrypy-27         3.2.2 -> 10.2.2         * upgrade?
* library/python-2/coverage-27         4.3.4 -> 4.4.1          * upgrade?
* library/python-2/jsonschema-27       2.5.1 -> 2.6.0          * upgrade?
* library/python-2/lxml-27             3.7.2 -> 3.7.3          * upgrade?
* library/python-2/m2crypto-27         0.24.0 -> 0.26.0        * upgrade?
* library/python-2/numpy-27            1.12.1 -> 1.13.1        * upgrade?
* library/python-2/pylint-27           1.7.1 -> 1.7.2          * upgrade?
* library/python-2/pyopenssl-27        0.11 -> 17.1.0          * upgrade?
* library/python-2/setuptools-27       0.6.11 -> 36.0.1        * upgrade?
* library/python-2/simplejson-27       3.10.0 -> 3.11.1        * upgrade?

**Comment by postwait** [comment]
I upgraded all of those to find that pkg complete failed.  It relies on the old versions of all of that stuff.  Maybe you'll have better luck than I did.  CherryPy was the most obvious catastrophy.

**Comment by citrus-it** [comment]
Thanks, appreciate the feedback.

**Comment by citrus-it** [comment]
All python modules are now upgraded and `pkg(5)` has been update accordingly. Closing issue.
