### ISSUE TITLE
zpool replace command returns internal error: out	of memory

### ISSUE THREAD

**Issue by PaulJochum** [omniosorg/omnios-build#524]
Hi All:

Last Saturday, I updated my servers to the latest version of OmniOS-CE
(r151024j), and today, while trying to replace a drive, I received the
following error message;

```
#  zpool replace zfs_pool c11t5000C5003A017D5Bd0 c11t5000C5003A39950Bd0
internal error: out of memory
```

Some information about my system:

```
# uname -a
SunOS lss-nfsa05 5.11 omnios-r151024-e482f10563 i86pc i386 i86pc
```
```
root@lss-nfsa05:~# uptime
 09:20:28  up   0:18,  3 users,  load average: 0.41, 0.30, 0.23


load averages:  0.38,  0.30,  0.23;               up 0+00:19:09 09:20:45
61 processes: 60 sleeping, 1 on cpu
CPU states: 99.3% idle,  0.0% user,  0.7% kernel,  0.0% iowait, 0.0% swap
Kernel: 1623 ctxsw, 1 trap, 1446 intr, 254 syscall, 1 flt
Memory: 128G phys mem, 118G free mem, 4096M total swap, 4096M free swap
```

I have tried rebooting my system and also exporting and importing the
zfs_pool filesystem, but neither step helped.

Any suggestions on what to try next, or what info to collect to help
debug this?

thanks,
Paul

**Comment by oetiker** [comment]
things that come to mind:

* making sure no ulimits are active
* adding more swap ... like 150 GB of swap or so (illumos afaik still does conservative memory allocation ... )
