### ISSUE TITLE
Improve kayak-kernel build to get bins from PREBUILT_ILLUMOS

### ISSUE THREAD

**Issue by hadfl** [omniosorg/omnios-build#59]
cf. https://github.com/omniosorg/omnios-build/pull/55#issuecomment-315354335

**Comment by danmcd** [comment]
Be warned, you'll need to get them from PREBUILT_ILLUMOS that only does non-debug, OR you can/should retrieve the binaries from the BUILDSEND filesystem that you populate to make the "zfs recv" image.

**Comment by citrus-it** [comment]
This will simplify the build zone setup. It will still need `fs-allowed=ufs` to allow mounting the miniroot lofi device but the loopback mounts could go.

**Comment by citrus-it** [comment]
This will also make an end-to-end run right for kayak. At present, the kayak-kernel picks up the binaries from the *running* system which are potentially older than those being built.
