### ISSUE TITLE
Remove omniti-ms dependency for building java packages

### ISSUE THREAD

**Issue by citrus-it** [omniosorg/omnios-build#6]
Building the `runtime/java` and `developer/java/jdk` OmniOS packages currently requires the installation of some packages from the `omniti-ms` repository. These should be replaced by packages from the `omnios-extra` repository.

The required packages are:
* omniti/developer/build/ant (installs in `/opt/omni`)
* omniti/library/freetype2 (installs in `/opt/omni`)

and installing `ant` also installs:
* omniti/runtime/perl (in `/opt/OMNIperl`)
* omniti/runtime/python-26 (in `/opt/python26`)
which may not be required.

**Comment by postwait** [comment]
I've advocated for a long time just dropping poold from omnios and thus freeing us from Java.  Couldn't swing that in the old days, but I'd be a big fan if no Java was shipped at all.  It's for one app and almost never a useful version of Java for the operators of the system or their users.

**Comment by oetiker** [comment]
we might want to move java itself to the extra repo

**Comment by hadfl** [comment]
nah, it is needed to run `poold`. so at least one version has to remain in core.

**Comment by postwait** [comment]
I'd like to see poold dropped from OmniOS (simply not built, packaged or provided) -- I'm not suggesting removing it from illumos entirely as I think that would not fly. SmartOS doesn't ship poold either FWIW.

**Comment by citrus-it** [comment]
Yep, we might end up doing that but let's leave this issue as a placeholder for now and decide when things settle down a bit. We have a solution for now but didn't want to forget this.

**Comment by ptribble** [comment]
It's not just poold. The following also need java

libdns_sd
libdtrace_jni
printmgr
slp
libadt_jni
libzfs_jni

and getting rid of all of those might be more tricky. What we could do with is an IDONTWANTANYTHINGTODOWITHJAVA build flag for illumos that just suppresses all of them, perhaps.

**Comment by postwait** [comment]
To be clear, that is what I'm suggesting.  It hasn't caused SmartOS any problems; rather it freed them from tragic baggage.
