### ISSUE TITLE
Remove omniti-ms dependency for building iso-codes package

### ISSUE THREAD

**Issue by citrus-it** [omniosorg/omnios-build#7]
Building the `data/iso-codes` OmniOS package currently requires the installation of a package from the `omniti-ms` repository. This should be replaced by a package from the `omnios-extra` repository.

The required package is:
* omniti/runtime/python-34 (installs in `/opt/python34`)

**Comment by oetiker** [comment]
hmmm don't we have enough power on board to do this with on-board tools ?

**Comment by oetiker** [comment]
https://anonscm.debian.org/cgit/pkg-isocodes/iso-codes.git/tree/bin ugly ugly python code :) we do have perl 24 with awesome unicode power on board ...

**Comment by citrus-it** [comment]
I should have said "either replace with a package from our own repository, or otherwise remove the dependency"... either is fine!

**Comment by citrus-it** [comment]
We don't want to add python 3 to the core - easiest is to have it in the auxiliary repo but it isn't an immediate priority.

**Comment by danmcd** [comment]
Yeah, python3 is *REQUIRED* for iso-codes.  Very VERY annoying.  I think I had an open issue on the OmniTI omnios-build about what in omnios-build still needs outside help.

**Comment by hadfl** [comment]
since it is only a build and not a run-time requirement i would for the moment stick to use it as is. we can always come up with a better solution later.

**Comment by oetiker** [comment]
hmm which package actually depends on iso-codes ?

**Comment by oetiker** [comment]
maybe we could move it to omnios-extra
