### ISSUE TITLE
Toshiba Persistent Write Cache, cache flushing

### ISSUE THREAD

**Issue by jozevolf** [omniosorg/omnios-build#845]
Hello,

I have sent this to the Toshiba support. Any comment/experience on Toshiba drives w/ Persistent Write Cache behavior on OmniOS?

> Dear Sir/Madam,
> 
> I have decided to use Toshiba Enterprise hard drives in my future ZFS systems because of the Persistent Write Cache function which I find as an excellent idea. I've ordered a new system to test this function before using these drives in the future. The system has 10 MG06ACA10TE drives which are attached to LSI SAS HBA in IT mode. Motherboard is Supermicro X10SDV-7TP4F with integrated Broadcom 2116 SAS controller.
> 
> The problem I have is that drives apparently do not ignore cache flush commands and they actually do the flush before acknowledging it to the host that the data is stored in non-volatile memory/on platters. (This is how Enterprise SSDs with power loss protection/capacitors behave). Small random SYNC writes to the drives are very slow because of that. I guess these hard drives should behave the same if their cache is really non-volatile. At least this is how I understand the anatomy of PWC/PLP.
> 
> I can define the model of the drive as having a non-volatile cache in my operating system settings (OmniOS) so it does not do cache flush for the SYNC writes. I do this by adding the following to /kernel/drv/sd.conf:
> 
> sd-config-list = "ATA     TOSHIBA MG06ACA1","cache-nonvolatile:true";
> 
> However I do this only based on trust in your promise that the write cache of these drives is truly protected by PWC. I guess the drives should behave differently and do not do the actual flush of the cache when being told to. They should just acknowledge it.
> 
> Could you give me some more information/guidance on PWC and cache flushing?
> 
> Best regards,
> Joze Volf
> iLab d.o.o.

**Comment by oetiker** [comment]
I am not aware of any experience with this device from ours side
