### ISSUE TITLE
Cannot build library/python-2/pycurl-27 in UTF-8 locale.

### ISSUE THREAD

**Issue by citrus-it** [omniosorg/omnios-build#9]
As per summary, package does not build if locale is UTF-8 (and possible other non-C ones).

```
--- setup.py (32) build
Running: /usr/bin/python2.7 ./setup.py build
Using curl-config (libcurl 7.54.0)
Traceback (most recent call last):
  File "./setup.py", line 824, in <module>
    ext = get_extension(sys.argv, split_extension_source=split_extension_source)
  File "./setup.py", line 498, in get_extension
    ext_config = ExtensionConfiguration(argv)
  File "./setup.py", line 71, in __init__
    self.configure()
  File "./setup.py", line 212, in configure_unix
    for arg in split_quoted(optbuf):
  File "/usr/lib/python2.7/distutils/util.py", line 257, in split_quoted
    if s[end] in string.whitespace: # unescaped, unquoted whitespace: now
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 6: ordinal not in range(128)
--- build failed
```

Possible fixes are to include LC_CTYPE=C in the package build.sh or lib/config.sh or lib/site.sh. When we work out the best approach, we should make the change.

**Comment by oetiker** [comment]
Do the build scripts not control locale settings at build time ? If not, that would be important todo, because otherwise we might up with packages that actually take the  into account.

I think best would be if the build script actually cleaned out all environment variable settings except for those we explicitly want set.

**Comment by ptribble** [comment]
OI hit this a while back resulting in either a pythin workaround or an illumos fix (whichever comes soonest):

https://www.illumos.org/issues/8361
