### ISSUE TITLE
dtrace: failed to compile script Preprocessor not found

### ISSUE THREAD

**Issue by cneira** [omniosorg/omnios-build#991]
Trying a Dtrace script this error was found, which is the same as https://github.com/joyent/pkgsrc-legacy/issues/22

rmustacc's answer to this issue.
https://github.com/joyent/pkgsrc-legacy/issues/22#issuecomment-10216557

Installing gcc and then creating the symlink solves the issue 
```bash
pfexec ln -sf /opt/local/gcc6/bin/cpp /usr/lib/cpp
```

I think we should add a c compiler in the base system as it's needed to use Dtrace.

**Comment by citrus-it** [comment]
We just need to make the `dtrace` package dependant on `developer/macro/cpp` since that provides `/usr/lib/cpp`

```
reaper# pkg search path:/usr/lib/cpp
INDEX      ACTION VALUE       PACKAGE
path       file   usr/lib/cpp pkg:/developer/macro/cpp@0.5.11-0.151026
```
```
reaper# pkgtree -U depends dtrace

|------(    require)--pkg://omnios/developer/dtrace@0.5.11-0.151026:20180420T093101Z
| pkg://omnios/consolidation/osnet/osnet-incorporation
| pkg://omnios/system/library/math@0.5.11-0.151026
| pkg://omnios/system/library@0.5.11-0.151026
| pkg://omnios/SUNWcs@0.5.11-0.151026
```
