### ISSUE TITLE
libc-runtime is missing from base

### ISSUE THREAD

**Issue by cneira** [omniosorg/omnios-build#992]
I installed Rust from pkgsrc then trying to compile https://github.com/joyent/statemap on OmniOSce failed as crt1.o was not on the system, talking with  jperkin in IRC he stated that this file should be provided by the platform, I agree on that statement. 
Could we add libc-runtime to base ?

**Comment by citrus-it** [comment]
`c-runtime` is not needed to run any software so isn't something that is needed in base.
If you want to build any software on OmniOS, make sure `developer/build-essential` is installed and that will provide everything you need, including `c-runtime`.
